config/routes.rb
InitialRelease::Application.routes.draw do

  resources :cards

  match '/card_clear/(:id)' => 'card_items#card_clear', :as => 'card_clear'
  match '/card_conversion/:act/:id' => 'card_items#card_conversion', :as => 'card_conversion'
  resources :card_items

  match '/login' => 'account#login', :as => 'login'
  match '/logout' => 'account#logout', :as => 'logout'
  match '/authenticate' => 'account#authenticate', :as => 'authenticate'

  match '/find/:text' => 'pages#find'

  resources :users
  resources :pages

  match '/move_menu/:id/:position' => 'menus#move', :as => 'move_menu'
  match '/visible_menu/:id/:value' => 'menus#visible', :as => 'visible_menu'
  match '/move_product/:id/:position' => 'products#move', :as => 'move_product'
  match '/del_image_product/:id/:image' => 'products#del_image', :as => 'del_image_product'

  match '/product_info/:id' => 'pages#product_info', :as => 'product_info'
  match '/category/(:id)' => 'pages#category', :as => 'category'

  resources :products
  resources :menus

  root :to => 'pages#show', :id => 1

	match ':hiperlink' => "products#show", :as => 'hiperlink'

end

app/models/menu.rb
class Menu < ActiveRecord::Base
  acts_as_nested_set
  attr_accessible :name, :parent_id
  has_many :products, :dependent => :destroy
end

app/controllers/menus_controller.rb
#encoding: utf-8
class MenusController < ApplicationController
	before_filter :have_access

  def move
    @menu = Menu.find(params[:id])
    case params[:position]
      when 'up'
        Menu.find(params[:id]).move_left if @menu != Menu.where(:parent_id=>@menu.parent_id).order('lft').first
      when 'down'
        Menu.find(params[:id]).move_right if @menu != Menu.where(:parent_id=>@menu.parent_id).order('lft').last
      when 'first'
        while @menu != Menu.where(:parent_id=>@menu.parent_id).order('lft').first
          Menu.find(params[:id]).move_left
        end
      when 'last'
        while @menu != Menu.where(:parent_id=>@menu.parent_id).order('lft').last
          Menu.find(params[:id]).move_right
        end
    end
    redirect_to :action=>'index', :parent_id => @menu.parent_id
  end

  def visible
    @menu = Menu.find(params[:id])
    params[:value] == 'true' ? @menu.visible = true : @menu.visible = false
    @menu.save
    redirect_to :action=>'index', :parent_id => @menu.parent_id
  end

  # GET /menus
  # GET /menus.xml
  def index
    params[:parent_id] == nil ? @menus = Menu.roots : @menus = Menu.where(:parent_id=> params[:parent_id]).order('lft')#.where(:visible=>true) #.leaves

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @menus }
    end
  end

  # GET /menus/1
  # GET /menus/1.xml
  def show
    @menu = Menu.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @menu }
    end
  end

  # GET /menus/new
  # GET /menus/new.xml
  def new

    params[:parent_id] == nil ? @menu = Menu.new : @menu = Menu.new(:parent_id => params[:parent_id])

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @menu }
    end
  end

  # GET /menus/1/edit
  def edit
    @menu = Menu.find(params[:id])
  end

  # POST /menus
  # POST /menus.xml
  def create
    @menu = Menu.new(params[:menu])

    respond_to do |format|
      if @menu.save
        format.html { redirect_to(:action=>'index', :parent_id => @menu.parent_id) }
        format.xml  { render :xml => @menu, :status => :created, :location => @menu }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @menu.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /menus/1
  # PUT /menus/1.xml
  def update
    @menu = Menu.find(params[:id])

    respond_to do |format|
      if @menu.update_attributes(params[:menu])
        format.html { redirect_to(@menu, :notice => 'Menu was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @menu.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /menus/1
  # DELETE /menus/1.xml
  def destroy
    @menu = Menu.find(params[:id])
    @menu.destroy

    respond_to do |format|
      format.html { redirect_to(menus_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/views/menus/_form.html.haml
= form_for(@menu) do |f|
	= f.hidden_field :parent_id, :value=>@menu.parent_id
	- if @menu.errors.any?
		#error_explanation
			%h2= pluralize(@menu.errors.count, "error")
			%ul
				- @menu.errors.full_messages.each do |msg|
					%li= msg
	.field{:style=>"margin-top:20px"}
		= f.label 'Название'
		.input
			= f.text_field :name, :class=>'span9'
		.actions
			= f.submit 'сохранить', :class=>'btn info'
			- if @menu.parent
				= link_to 'отменить', {:controller=>'menus', :action=>'index', :parent_id=>@menu.parent_id}, :class=>'btn info'
			- else
				= link_to 'отменить', menus_path, :class=>'btn info'

app/views/menus/edit.html.haml
%h3.title
	Редактирование раздела
	= @menu.name
= render 'form'

app/views/menus/index.html.haml
%h3.title
	Раздел:
	= params[:parent_id] ? (link_to Menu.find(params[:parent_id]).name, {:controller=>'menus', :action=>'index', :parent_id=>Menu.find(params[:parent_id]).parent_id}) : 'Корневой раздел'
	- if params[:parent_id]
		= link_to 'добавить раздел', {:controller=>'menus', :action=>'new', :parent_id=>params[:parent_id]}, :class=>'btn info'
	- else
		= link_to 'добавить раздел', {:controller=>'menus', :action=>'new'}, :class=>'btn info'
%br/
%table.zebra-striped
	%tr
		%th Название
		%th Раздел
		%th{:style=>'text-align:center;width:120px;'} &nbsp;
		%th{:style=>'width:25px;'} &nbsp;
		%th{:style=>'width:25px;'} &nbsp;
		%th{:style=>'width:25px;'} &nbsp;
	- @menus.each do |menu|
		%tr
			%td= link_to menu.name, {:controller=>'menus', :action=>'index', :parent_id=>menu}
			%td= menu.parent.name if menu.parent
			%td{:style=>'text-align:center;'}
				= link_to move_menu_path(:position=>'first', :id=>menu.id), :class=>'with-img' do
					= image_tag '/images/first.png'
				= link_to move_menu_path(:position=>'up', :id=>menu.id), :class=>'with-img' do
					= image_tag '/images/up.png'
				= link_to move_menu_path(:position=>'down', :id=>menu.id), :class=>'with-img' do
					= image_tag '/images/down.png'
				= link_to move_menu_path(:position=>'last', :id=>menu.id), :class=>'with-img' do
					= image_tag '/images/last.png'
			%td{:style=>'text-align:center;'}
				- if menu.visible
					= link_to visible_menu_path(:value=>'false', :id=>menu.id), :class=>'with-img' do
						= image_tag '/images/visible.png'
				- else
					= link_to visible_menu_path(:value=>'true', :id=>menu.id), :class=>'with-img' do
						= image_tag '/images/notvisible.png'
			%td{:style=>'text-align:center;'}
				= link_to edit_menu_path(menu), :class=>'with-img' do
					= image_tag '/images/edit.png'
			%td{:style=>'text-align:center;'}
				= link_to menu, :confirm => 'Are you sure?', :method => :delete, :class=>'with-img' do
					= image_tag '/images/del.png'
%h3.title{:style=>'margin-top:20px;'}
	Товары в разделе
	- if params[:parent_id]
		= link_to 'добавить товар', {:controller=>'products', :action=>'new', :parent_id=>params[:parent_id]}, :class=>'btn info'
	- else
		= link_to 'добавить товар', {:controller=>'products', :action=>'new'}, :class=>'btn info'
%br/
%table.zebra-striped.products
	%tr
		%th{:style=>'width:110px;'} Фото
		%th Информация
		%th{:style=>'text-align:center'} Цена
		%th{:style=>'width:25px;'} &nbsp;
		%th{:style=>'width:25px;'} &nbsp;
	- @products = Product.where(:menu_id=>params[:parent_id]).order('position')
	- if @products
		- @products.each do |product|
			%tr
				%td= product.images == [] ? '' : image_tag(product.images.first.photo.url(:thumb), :class=>'ui-corner-all photo')
				%td
					%h6= link_to(product.name, product.datasheet.url)
					%p!= truncate(product.info, :length=>140, :omision=>'...')
				%td{:style=>'text-align:center;vertical-align:top;'}
					%span.label.notice{:style=>'font-size:13px;'}= number_to_currency(product.price, :unit=>'руб', :precision=>0, :format=>"%n %u", :delimiter => " ") if product.price
				%td{:style=>'text-align:center;'}
					= link_to edit_product_path(product), :class=>'with-img' do
						= image_tag '/images/edit.png'
				%td{:style=>'text-align:center;'}
					= link_to product, :confirm => 'Are you sure?', :method => :delete, :class=>'with-img' do
						= image_tag '/images/del.png'

app/views/menus/new.html.haml
%h3.title
	Добавление раздела в 
	= params[:parent_id] ? Menu.find(params[:parent_id]).name : 'Корневой раздел'
= render 'form'

app/views/menus/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @menu.name %>
</p>

<p>
  <b>Parent:</b>
  <%= @menu.parent_id %>
</p>

<p>
  <b>Lft:</b>
  <%= @menu.lft %>
</p>

<p>
  <b>Rgt:</b>
  <%= @menu.rgt %>
</p>


<%= link_to 'Edit', edit_menu_path(@menu) %> |
<%= link_to 'Back', menus_path %>