config/routes.rb
InitialRelease::Application.routes.draw do

  resources :cards

  match '/card_clear/(:id)' => 'card_items#card_clear', :as => 'card_clear'
  match '/card_conversion/:act/:id' => 'card_items#card_conversion', :as => 'card_conversion'
  resources :card_items

  match '/login' => 'account#login', :as => 'login'
  match '/logout' => 'account#logout', :as => 'logout'
  match '/authenticate' => 'account#authenticate', :as => 'authenticate'

  match '/find/:text' => 'pages#find'

  resources :users
  resources :pages

  match '/move_menu/:id/:position' => 'menus#move', :as => 'move_menu'
  match '/visible_menu/:id/:value' => 'menus#visible', :as => 'visible_menu'
  match '/move_product/:id/:position' => 'products#move', :as => 'move_product'
  match '/del_image_product/:id/:image' => 'products#del_image', :as => 'del_image_product'

  match '/product_info/:id' => 'pages#product_info', :as => 'product_info'
  match '/category/(:id)' => 'pages#category', :as => 'category'

  resources :products
  resources :menus

  root :to => 'pages#show', :id => 1

	match ':hiperlink' => "products#show", :as => 'hiperlink'

end

app/models/product.rb
class Product < ActiveRecord::Base
  #acts_as_nested_set
  acts_as_list :scope => "position"
  belongs_to :menu
  has_attached_file :datasheet #, :styles => { :thumb=> "100x100#", :small  => "250x250>", :normal => "600x600>" }
  has_many :images, :dependent => :destroy
  has_many :card_items
end

app/controllers/products_controller.rb
#encoding: utf-8
class ProductsController < ApplicationController
  #layout 'main_layout', :only=>'show'
  layout 'application', :except=>'show'
  before_filter :have_access, :except => [:show]

    def del_image
      @product = Product.find(params[:id])
      @image = Image.find(params[:image])
      @image.destroy
      #@product.images.where(:id=>params[:image]).destroy
      redirect_to :controller=>'products', :action=>'edit', :id => @product.id, :parent_id => @product.menu_id
    end

    def move
    @product = Product.find(params[:id])
    case params[:position]
      when 'up'
        Product.find(params[:id]).move_higher #(params[:id]).move_left if @product != Product.where(:menu_id=>@product.menu_id).order('lft').first
      when 'down'
        Product.find(params[:id]).move_lower #.move_right if @product != Product.where(:menu_id=>@product.menu_id).order('lft').last
      when 'first'
        #while @product != Product.where(:menu_id=>@product.menu_id).order('lft').first
          Product.find(params[:id]).move_to_top #.move_left
        #end
      when 'last'
        #while @product != Product.where(:menu_id=>@product.menu_id).order('lft').last
          Product.find(params[:id]).move_to_bottom #.move_right
        #end
    end
    redirect_to :controller=>'menus', :action=>'index', :parent_id => @product.menu_id
  end

  # GET /products
  # GET /products.xml
  def index
    @products = Product.all
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @products }
    end
  end

  # GET /products/1
  # GET /products/1.xml
  def show
  	if params[:hiperlink]
	    @product = Product.find_by_hiperlink(params[:hiperlink])
    else
      @product = Product.find(params[:id])
    end
    if @product == nil
    	redirect_to pages_path
    else
	    render 'show', :layout=>'main_layout'
	  end
  end

  # GET /products/new
  # GET /products/new.xml
  def new
    @product = Product.new(:menu_id=>params[:parent_id])

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.xml
  def create
    @product = Product.new(params[:product])
    @product.info = params[:product][:info] if params[:product][:info]
    #@product.info = params[:product][:info].gsub("<", "&alt").gsub(">", "&alt").gsub("\r\n", "<br />") if params[:product][:info]
    #фото
    if params[:photos]
      params[:photos].each do |photo|
        image = Image.new(:photo=>photo)
        @product.images << image
    	end
    end
    @product.position = Product.all.size + 1
    respond_to do |format|
      if @product.save
        format.html { redirect_to :controller=>'menus', :action=>'index', :parent_id => @product.menu_id }
        format.xml  { render :xml => @product, :status => :created, :location => @product }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @product.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.xml
  def update
    @product = Product.find(params[:id])
    #фото
    if params[:photos]
      params[:photos].each do |photo|
        image = Image.new(:photo=>photo)
        @product.images << image
      end
      @product.save
    end

    respond_to do |format|
      if @product.update_attributes(params[:product])
      	@product.info = params[:product][:info] if params[:product][:info]
      	#@product.info = params[:product][:info].gsub("<", "&alt").gsub(">", "&alt").gsub("\r\n", "<br />") if params[:product][:info]
      	@product.save
        format.html { redirect_to  :controller=>'menus', :action=>'index', :parent_id => @product.menu_id }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @product.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.xml
  def destroy
    @product = Product.find(params[:id])
    menu_id =  @product.menu_id
    @product.destroy

    respond_to do |format|
      format.html { redirect_to :controller=>'menus', :action=>'index', :parent_id => menu_id }
      format.xml  { head :ok }
    end
  end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.haml
= javascript_include_tag :ckeditor
= form_for(@product, :html => { :multipart => true }) do |f|
	= f.hidden_field :menu_id, :value=>@product.menu_id
	- if @product.errors.any?
		#error_explanation
			%h6= pluralize(@product.errors.count, "error")
			%ul
				- @product.errors.full_messages.each do |msg|
					%li= msg
	.field{:style=>"margin-top:20px"}
		= f.label 'Документация'
		.input
			= f.file_field :datasheet, :class=>"input-file", :style=>"background:#eee;"
	.field
		= f.label 'Название'
		.input
			= f.text_field :name, :class=>"span9"
	.field
		= f.label 'Описание'
		.input{:style=>"height:280px;width:520px;"}
			= cktext_area(:product, :info, :toolbar => 'Small')
			=# f.text_area :info, :class=>"span9", :style=>"height:100px;"
	.field
		= f.label 'Цена'
		.input
			= f.text_field :price, :class=>'span9'
	.field
		= f.label 'Ссылка'
		.input
			= f.text_field :hiperlink, :class=>'span9'
	#photo-pres{:style=>'display:block;margin:10px 70px 10px 150px;'}
		- @product.images.each do |image|
			.photo-pres{:style=>'margin:5px 5px 0 0;display:inline;'}
				= image_tag(image.photo.url(:thumb), :class=>'ui-corner-all photo')
				= link_to del_image_product_path(:id=>@product.id, :image=>image.id), :style=>'position:relation;margin-left:-25px;' do
					= image_tag '/images/del.png'
	#photo-list.field
		= f.label 'Добавить фото', :id=>'choose_file'
		- 5.times do |num|
			.input
				%input{:type=>'file', :name=>'photos[]', :class=>'input-file file-list', :style=>'background:#eee;', :id=>"file-list-#{num}"}
				=# file_field(:product, 'photos[]', :class=>"input-file", :style=>"background:#eee;")
	.actions
		= f.submit 'сохранить данные', :class=>"btn info"
		- if @product.menu
			= link_to 'отменить', {:controller=>'menus', :action=>'index', :parent_id=>@product.menu.id}, :class=>'btn info'
		- else
			= link_to 'отменить', menus_path, :class=>'btn info'

app/views/products/edit.html.haml
%h3.title
	Редактирование товара: 
	= @product.name
= render 'form'

app/views/products/index.html.erb
<h1>Listing products</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Info</th>
    <th>Balance</th>
    <th>Price</th>
    <th>Menu</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @products.each do |product| %>
  <tr>
    <td><%= product.name %></td>
    <td><%!= product.info %></td>
    <td><%= product.balance %></td>
    <td><%= product.price %></td>
    <td><%= product.menu_id %></td>
    <td><%= link_to 'Show', product %></td>
    <td><%= link_to 'Edit', edit_product_path(product) %></td>
    <td><%= link_to 'Destroy', product, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.haml
%h3.title
	Добавление товара в раздел: 
	= params[:parent_id] ? Menu.find(params[:parent_id]).name : 'Корневой раздел'
= render 'form'

app/views/products/show.html.haml
= javascript_include_tag "autoadvance.js", "autoadvance-script.js"
= stylesheet_link_tag "autoadvance-styles.css"
%h2.title= truncate(@product.name, :length=>20, :ommission=>'...')
%table.product-info
	%tr
		%td{:rowspan=>2}
			-##slideshow
			%ul#galery{:style=>'float:left'}
				-#.slides
				- @product.images.each do |f|
					%li
						= link_to f.photo.url(:normal) do
							= image_tag f.photo.url(:small) #, :style => 'margin:20px 20px auto auto;', :class => 'image-list'
			-#	%span.arrow.previous
			-#	%span.arrow.next
		%td.price
			= number_to_currency(@product.price, :unit=>'руб', :precision=>0, :format=>"%n %u", :delimiter => " ") if @product.price
		%td.add-card
			= button_to 'добавить в корзину', card_items_path(:product_id=>@product.id), :remote=>true, :class=>'btn info' if @product.price
	%tr
		%td{:colspan => 2}
			%h3{:style=>"margin-top:50px;font:normal 14px 'Arial';line-height:26px;"}!= @product.info
	%tr
		%td{:colspan => 3, :style=>'vertical-align:bottom;background:#eee;'}
			- if @product.datasheet.url != '/datasheets/original/missing.png'
				%span{:style=>'font:normal 14px Arial;'} Datasheet:
				= link_to @product.datasheet_file_name, @product.datasheet.url
			- else
				!= "&nbsp;"