config/routes.rb
InitialRelease::Application.routes.draw do

  resources :cards

  match '/card_clear/(:id)' => 'card_items#card_clear', :as => 'card_clear'
  match '/card_conversion/:act/:id' => 'card_items#card_conversion', :as => 'card_conversion'
  resources :card_items

  match '/login' => 'account#login', :as => 'login'
  match '/logout' => 'account#logout', :as => 'logout'
  match '/authenticate' => 'account#authenticate', :as => 'authenticate'

  match '/find/:text' => 'pages#find'

  resources :users
  resources :pages

  match '/move_menu/:id/:position' => 'menus#move', :as => 'move_menu'
  match '/visible_menu/:id/:value' => 'menus#visible', :as => 'visible_menu'
  match '/move_product/:id/:position' => 'products#move', :as => 'move_product'
  match '/del_image_product/:id/:image' => 'products#del_image', :as => 'del_image_product'

  match '/product_info/:id' => 'pages#product_info', :as => 'product_info'
  match '/category/(:id)' => 'pages#category', :as => 'category'

  resources :products
  resources :menus

  root :to => 'pages#show', :id => 1

	match ':hiperlink' => "products#show", :as => 'hiperlink'

end

app/models/card_item.rb
class CardItem < ActiveRecord::Base
	belongs_to :card
	belongs_to :product
end

app/controllers/card_items_controller.rb
class CardItemsController < ApplicationController
  layout 'main_layout', :only =>'index'

	def create
		id = rand(1234567890)
    session[:card] = Card.new( :id => id) unless session[:card]
    session[:card][:card_item] = {} unless session[:card][:card_item]
    idItem = 0
    @product = Product.find(params[:product_id])
    count = 1
    session[:card][:card_item].each do |item, item_params|
			if item_params[:product_id] == @product.id
				count = item_params[:count] + 1
				idItem = item.to_i #item_params[:id]
			end
    end
    idItem = rand(1234567890) if idItem == 0
    session[:card][:card_item][idItem] = {:product_id=>@product.id, :count=>count, :price=>@product.price, :summ=>@product.price*count}
    session[:card].count = session[:card][:card_item].size
  end

  def index
  	if session[:card]
	    #@card_items = []
	    #session[:card][:card_item].each do |item, item_params|
	    #	@card_items << CardItem.new(
	    #												:id=>item_params[:id], #item.to_i,
	    #												:product_id=>item_params[:product_id],
	    #												:count=>item_params[:count],
	    #												:price=>item_params[:price])
	    #end
	  else
	  	@card_items = nil
	  end
  end

	def card_clear
		if params[:id]
			current_card[:card_item].delete(params[:id].to_i)
			current_card.count -= 1
			session[:card] = nil if current_card.count == 0
		else
			session[:card] = nil
		end
		redirect_to(card_items_url)
	end

	def card_conversion
		product_id = session[:card][:card_item][params[:id].to_i][:product_id]
		count = session[:card][:card_item][params[:id].to_i][:count]
		price = session[:card][:card_item][params[:id].to_i][:price]
		if params[:act] == 'true'
			count += 1
			summ = count * price
			session[:card][:card_item][params[:id].to_i] = {
															:product_id=>product_id,
															:count=>count,
															:price=>price,
															:summ=>summ}
		else
			count -= 1
			if count == 0
				current_card[:card_item].delete(params[:id].to_i)
				current_card.count -= 1
				session[:card] = nil if current_card.count == 0
			else
				summ = count * price
				session[:card][:card_item][params[:id].to_i] = {
															:product_id=>product_id,
															:count=>count,
															:price=>price,
															:summ=>summ}
			end
		end
		redirect_to(card_items_url)
	end

  def show
    @card_item = CardItem.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @card_item }
    end
  end

  # GET /card_items/new
  # GET /card_items/new.xml
  def new
    @card_item = CardItem.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @card_item }
    end
  end

  # GET /card_items/1/edit
  def edit
    @card_item = CardItem.find(params[:id])
  end

  # POST /card_items
  # POST /card_items.xml


  # PUT /card_items/1
  # PUT /card_items/1.xml
  def update
    @card_item = CardItem.find(params[:id])

    respond_to do |format|
      if @card_item.update_attributes(params[:card_item])
        format.html { redirect_to(@card_item, :notice => 'Card item was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @card_item.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /card_items/1
  # DELETE /card_items/1.xml
  def destroy
    @card_item = CardItem.find(params[:id])
    @card_item.destroy

    respond_to do |format|
      format.html { redirect_to(card_items_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/card_items_helper.rb
module CardItemsHelper
end

app/views/card_items/_form.html.erb
<%= form_for(@card_item) do |f| %>
  <% if @card_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@card_item.errors.count, "error") %> prohibited this card_item from being saved:</h2>

      <ul>
      <% @card_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product_id %><br />
    <%= f.text_field :product_id %>
  </div>
  <div class="field">
    <%= f.label :count %><br />
    <%= f.text_field :count %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :summ %><br />
    <%= f.text_field :summ %>
  </div>
  <div class="field">
    <%= f.label :card_id %><br />
    <%= f.text_field :card_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/card_items/create.js.erb
$('#cards').text("<%= escape_javascript('КОРЗИНА (' + current_card.count.to_s + ')') %>");

alert("Товар <%= @product.name %> добавлен в корзину", "");

app/views/card_items/edit.html.erb
<h1>Editing card_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @card_item %> |
<%= link_to 'Back', card_items_path %>

app/views/card_items/index.html.erb
<h2 class="title">Корзина товаров</h2>
<% if current_card %>
	<table style="width:650px;margin-bottom:20px;margin-top:20px;">
		<tr class="card-item-tr">
		  <th>Товар</th>
		  <th>Количество</th>
		  <th>Цена</th>
		  <th>Сумма</th>
		  <th></th>
		</tr>
		<% summ = 0 %>
		<% current_card[:card_item].each do |item, item_params| %>
			<% summ += item_params[:summ] %>
			<tr class="card-item-tr">
				<td><%= Product.find(item_params[:product_id]).name %></td>
				<td>
					<%= link_to card_conversion_path(:id=>item.to_s, :act=>'false') do %>
						<%=	image_tag "minus.png" %>
					<% end %>
					<%= item_params[:count] %>
					<%= link_to card_conversion_path(:id=>item.to_s, :act=>'true') do %>
						<%=	image_tag "plus.png" %>
					<% end %>
				</td>
				<td><%= number_to_currency(item_params[:price], :unit=>'руб', :precision=>0, :format=>"%n %u", :delimiter => " ") %></td>
				<td><%= number_to_currency(item_params[:summ], :unit=>'руб', :precision=>0, :format=>"%n %u", :delimiter => " ") %></td>
				<td><%= link_to card_clear_path(item.to_s), :confirm => 'вы уверены?', :method => :delete do %>
					<%=	image_tag "del.png" %>
				<% end %>
				</td>
			</tr>
		<% end %>
		</table>
	<span style="color:#0272BE;font: bold italic 18px Tahoma, Georgia, 'Times New Roman', Times, serif;">
		Общая сумма:&nbsp;
		<%= number_to_currency(summ, :unit=>'руб', :precision=>0, :format=>"%n %u", :delimiter => " ") %>
	</span>
	<%= link_to 'очистить корзину', card_clear_path, :confirm => 'вы уверены?', :method => :delete, :class => 'btn danger', :style=>'float:right; margin-right:50px;margin-bottom:20px;' %>
	<%= link_to 'оформить заказ', new_card_path, :class => 'btn primary', :style=>'float:right; margin-right:20px;margin-bottom:20px;' %>
<% else %>
	<h3 align='center'>Корзина пуста</h3>
<% end %>

<br />

app/views/card_items/new.html.erb
<h1>New card_item</h1>

<%= render 'form' %>

<%= link_to 'Back', card_items_path %>

app/views/card_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Product:</b>
  <%= @card_item.product_id %>
</p>

<p>
  <b>Count:</b>
  <%= @card_item.count %>
</p>

<p>
  <b>Price:</b>
  <%= @card_item.price %>
</p>

<p>
  <b>Summ:</b>
  <%= @card_item.summ %>
</p>

<p>
  <b>Card:</b>
  <%= @card_item.card_id %>
</p>

<p>
  <b>User:</b>
  <%= @card_item.user_id %>
</p>


<%= link_to 'Edit', edit_card_item_path(@card_item) %> |
<%= link_to 'Back', card_items_path %>