config/routes.rb
InitialRelease::Application.routes.draw do

  resources :cards

  match '/card_clear/(:id)' => 'card_items#card_clear', :as => 'card_clear'
  match '/card_conversion/:act/:id' => 'card_items#card_conversion', :as => 'card_conversion'
  resources :card_items

  match '/login' => 'account#login', :as => 'login'
  match '/logout' => 'account#logout', :as => 'logout'
  match '/authenticate' => 'account#authenticate', :as => 'authenticate'

  match '/find/:text' => 'pages#find'

  resources :users
  resources :pages

  match '/move_menu/:id/:position' => 'menus#move', :as => 'move_menu'
  match '/visible_menu/:id/:value' => 'menus#visible', :as => 'visible_menu'
  match '/move_product/:id/:position' => 'products#move', :as => 'move_product'
  match '/del_image_product/:id/:image' => 'products#del_image', :as => 'del_image_product'

  match '/product_info/:id' => 'pages#product_info', :as => 'product_info'
  match '/category/(:id)' => 'pages#category', :as => 'category'

  resources :products
  resources :menus

  root :to => 'pages#show', :id => 1

	match ':hiperlink' => "products#show", :as => 'hiperlink'

end

app/views/layouts/_menu.html.haml
%li
	= link_to  menu.name, category_path(menu)
	%ul
		= render :partial => "layouts/menu", :collection => menu.children.where(:visible=>true).order('lft')

app/views/layouts/application.html.haml
!!!
%html
	%head
		%title радиодетали
		= stylesheet_link_tag 'cupertino/jquery-ui-1.8.16.custom.css', 'bootstrap', 'treeview', 'layout'
		= javascript_include_tag :defaults, 'jquery.treeview.js', 'jquery.cookie.js'
		= csrf_meta_tag
	%body
		.header
		.row{:style=>"margin: 20px auto auto auto; width:1000px;"}
			.span4
				= link_to 'разделы и товары', menus_path
				%br/
				%br/
				= link_to 'страницы', pages_path
				%br/
				%br/
				= link_to 'заказы', cards_path
				%br/
				%br/
				%br/
				%br/
				= link_to 'выход', logout_path
			.span13{:style=>"background:#eee;width:740px;"}
				= yield

app/views/layouts/main_layout.html.haml
!!!
%html
	%head
		%title cqradio.ru
		= stylesheet_link_tag "../javascripts/fancybox/jquery.fancybox.css", 'jqGalScroll.css', 'cupertino/jquery-ui-1.8.16.custom.css', 'bootstrap', 'treeview.css', 'layout'
		= javascript_include_tag :defaults, "fancybox/jquery.fancybox.pack.js", 'jquery.treeview.js', 'jquery.cookie.js', 'jqgalscroll.js'
		= csrf_meta_tag
		= include_gritter
	%body
		= gflash
		= gritter_flash_messages
		#content
			= image_tag 'logo.png', :style=>'float:left; width:300px; margin-top:10px;'
			= image_tag 'TH-9000.png', :style=>'float:right; width:140px; margin-top: 5px;'
			%ul#top-link-text.pills
				- if params[:id] && params[:id] == 1 && controller_name == 'pages'
					%li.active= link_to 'ГЛАВНАЯ', root_path
				- else
					%li= link_to 'ГЛАВНАЯ', root_path
				- if action_name == 'category' || controller_name == 'products'
					%li.active= link_to 'ТОВАРЫ', category_path
				- else
					%li= link_to 'ТОВАРЫ', category_path
				- Page.where('id != 1').each do |page|
					- if params[:id] && params[:id] == page.id.to_s && controller_name == 'pages' && action_name != 'category'
						%li.active= link_to page.name, page_path(page)
					- else
						%li= link_to page.name, page_path(page)
				- if controller_name == 'card_items'
					- if !current_card
						%li.active= link_to 'КОРЗИНА', card_items_path, :id=>'cards'
					- else
						%li.active= link_to 'КОРЗИНА (' + current_card.count.to_s + ')', card_items_path, :id=>'cards'
				- else
					- if !current_card
						%li= link_to 'КОРЗИНА', card_items_path, :id=>'cards'
					- else
						%li= link_to 'КОРЗИНА (' + current_card.count.to_s + ')', card_items_path, :id=>'cards'
				-#%li
					= image_tag 'lock.png'
					= link_to 'Регистрация', root_path
					= link_to '/', '#', :id=>'enter-space'
					= link_to 'Вход', login_path
			-# 	%li
			-# 		= image_tag 'shopcart.png'
			-# 		= link_to 'Корзина', root_path
			.clear
			#find
				.field
					%input#find-text
				= link_to 'Поиск', root_path, :id=>'find-but'
			.row
				.span5
					%h2.product ТОВАРЫ
					%ul#main-menu
						-#%li= link_to Page.find(1).name, root_path
						-#%li= link_to 'ТОВАРЫ', category_path
						%ul#main-menu.menu-product
							- Menu.roots.where(:visible=>true).order('lft').each do |menu|
								= render :partial => "layouts/menu", :locals => {:menu=>menu }
							-# Menu.roots.where(:visible=>true).order('lft').each do |m_root|
								%li
									= link_to m_root.name, category_path(m_root)
								%ul#main-menu
									- m_root.children.where(:visible=>true).each do |m_child|
										%li
											= link_to m_child.name, category_path(m_child)
									- m_root.products.where(:visible=>true).each do |p_root|
										%li
											- if p_root.hiperlink
												= link_to p_root.name, hiperlink_path(p_root.hiperlink), :class=>'product'
											- else
												= link_to p_root.name, product_path(p_root), :class=>'product'
						-# Page.where('id != 1').each do |page|
							%li
								= link_to page.name, page_path(page)
					-#%h2.product{:style=>'margin-top:50px;'} НОВИНКА
					-# Product.where(:visible=>true).order('created_at DESC').limit(1).each do |prod|
						= link_to(product_path(prod)) do
							= image_tag(prod.images.first.photo.url(:thumb), :alt=>prod.name) if prod.images != []
							%span= truncate(prod.name, :ommission=>'...', :length=>15)
				.span12
					- if controller_name != 'products' && controller_name != 'account' && controller_name != 'cards'
						.sc_menu
							%ul.sc_menu
								- Product.where(:visible=>true).order('created_at DESC').limit(15).each do |prod|
									- if prod.images != []
										%li
											- if prod.hiperlink
												= link_to(hiperlink_path(prod.hiperlink)) do
													= image_tag(prod.images.first.photo.url(:thumb), :alt=>prod.name)
													%span= truncate(prod.name, :ommission=>'...', :length=>15)
											- else
												= link_to(product_path(prod)) do
													= image_tag(prod.images.first.photo.url(:thumb), :alt=>prod.name)
													%span= truncate(prod.name, :ommission=>'...', :length=>15)
					-#%h2.title Новые товары
					-#- Product.where(:visible=>true).order('created_at DESC').limit(3).each do |pr|
					-#	= link_to(product_path(pr), :class=>'rowbottom') do
					-#		= image_tag pr.images.first.photo.url(:thumb) if pr.images != []
					-#		.prod-name= truncate(pr.name, :length=>20, :ommission=>'...')
					-#		.prod-info= truncate(pr.info, :length=>50, :ommission=>'...')
					-#.clear
					.info
						= yield
			#layout_footer
		#footer
			%p
				%a{:href=>'http://yuliansait.ru', :title=>'юлиансайт.рф -- yuliansait.ru'} разработчик юлиансайт.рф